CREATE TABLE DEBTOR (
    DEBTOR_ID INT NOT NULL AUTO_INCREMENT,
    DEBTOR_NAME VARCHAR(20),
	DEBTOR_NICK VARCHAR(50) NOT NULL,
    DEBTOR_EMAIL VARCHAR(200) NOT NULL,
	PRIMARY KEY(DEBTOR_ID)
);

CREATE TABLE DEBT (
    DEBT_ID INT NOT NULL AUTO_INCREMENT,
	DEBTOR_ID INT NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    MONEY_VALUE DECIMAL(20, 2) NOT NULL,
	DATE_DEBT DATE NOT NULL,
	PAID BOOLEAN NOT NULL,
	SENDABLE BOOLEAN NOT NULL,
	PRIMARY KEY(DEBT_ID),
	FOREIGN KEY (DEBTOR_ID) REFERENCES DEBTOR(DEBTOR_ID)
);

INSERT INTO DEBTOR (DEBTOR_NAME, DESCRIPTION, EMAIL, MONEY_VALUE, DATE_DEBT, PAID, SENDABLE)
VALUES ("Fabiana", "Valor XPTO", "Fabiana_martins_oliveira@yahoo.com.br", '12.00', '2008-7-04', true, true);